openapi : 3.0.0
info:
  title: Social App
  description: Our First Social App in progress
  version: 1.0.1

servers:
  - url: http://localhost:4000/api/v1
    description: localhost version of our app
  - url: http://localhost:4000/api/v1
    description: This is just a dummy site.


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

